# Generated by Django 5.2.6 on 2025-09-06 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('price', models.IntegerField()),
                ('thumbnail', models.URLField()),
                ('category', models.CharField(choices=[('kit', 'Kit'), ('top', 'Top'), ('bottom', 'Bottom'), ('footwear', 'Footwear'), ('accessory', 'Accessory')], max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
